const sampleComic = [
    {
        BookName: "Galactic Adventures",
        AuthorName: "John Spacewalker",
        YearOfPublication: 2020,
        Price: 15.99,
        Discount: 10,
        NumberOfPages: 120,
        Condition: "new",
        description: "An epic sci-fi comic about intergalactic exploration.",
        Genre: "sci-fi"
    },
    {
        BookName: "Warrior's Honor",
        AuthorName: "Jane Soldier",
        YearOfPublication: 2018,
        Price: 9.99,
        Discount: 5,
        NumberOfPages: 90,
        Condition: "used",
        description: "A gripping story of a soldier's journey during the war.",
        Genre: "soldier"
    },
    {
        BookName: "Love Beyond Stars",
        AuthorName: "Alice Heart",
        YearOfPublication: 2019,
        Price: 12.50,
        Discount: 0,
        NumberOfPages: 110,
        Condition: "new",
        description: "A touching love story set in a sci-fi universe.",
        Genre: "love"
    },
    {
        BookName: "Battlefield Chronicles",
        AuthorName: "Peter Warhammer",
        YearOfPublication: 2021,
        Price: 14.75,
        Discount: 8,
        NumberOfPages: 130,
        Condition: "new",
        description: "An intense narrative of soldiers on a war-torn planet.",
        Genre: "war"
    },
    {
        BookName: "Family Ties",
        AuthorName: "Maria Bonds",
        YearOfPublication: 2017,
        Price: 8.99,
        Discount: 2,
        NumberOfPages: 100,
        Condition: "used",
        description: "A family overcomes struggles in an apocalyptic world.",
        Genre: "family"
    },
    {
        BookName: "Friendship's Voyage",
        AuthorName: "Tom Sailor",
        YearOfPublication: 2022,
        Price: 13.99,
        Discount: 7,
        NumberOfPages: 115,
        Condition: "new",
        description: "Friends embark on an adventure across galaxies.",
        Genre: "friendship"
    },
    {
        BookName: "Stellar Warzone",
        AuthorName: "George Blaster",
        YearOfPublication: 2016,
        Price: 10.50,
        Discount: 4,
        NumberOfPages: 95,
        Condition: "used",
        description: "A soldier battles enemies in a distant galaxy.",
        Genre: "soldier"
    },
    {
        BookName: "Hearts of Steel",
        AuthorName: "Emily Lovejoy",
        YearOfPublication: 2020,
        Price: 11.75,
        Discount: 3,
        NumberOfPages: 105,
        Condition: "new",
        description: "A love story of two warriors in a sci-fi setting.",
        Genre: "love"
    },
    {
        BookName: "Galactic Brotherhood",
        AuthorName: "Andrew Unity",
        YearOfPublication: 2021,
        Price: 14.99,
        Discount: 6,
        NumberOfPages: 125,
        Condition: "new",
        description: "The power of friendship in a galactic conflict.",
        Genre: "friendship"
    },
    {
        BookName: "The Final Stand",
        AuthorName: "Sarah Warhawk",
        YearOfPublication: 2019,
        Price: 9.50,
        Discount: 0,
        NumberOfPages: 110,
        Condition: "used",
        description: "A soldier makes a stand in the final battle of a war.",
        Genre: "war"
    },
    {
        BookName: "Cosmic Love",
        AuthorName: "Sophia Star",
        YearOfPublication: 2022,
        Price: 13.00,
        Discount: 10,
        NumberOfPages: 120,
        Condition: "new",
        description: "A romance between two beings from different galaxies.",
        Genre: "love"
    },
    {
        BookName: "Warrior's Journey",
        AuthorName: "Victor Valor",
        YearOfPublication: 2015,
        Price: 10.99,
        Discount: 5,
        NumberOfPages: 90,
        Condition: "used",
        description: "A soldier’s transformation from recruit to hero.",
        Genre: "soldier"
    },
    {
        BookName: "Galaxy Defenders",
        AuthorName: "Rex Starlord",
        YearOfPublication: 2020,
        Price: 12.99,
        Discount: 8,
        NumberOfPages: 115,
        Condition: "new",
        description: "A team of friends defends the galaxy from evil forces.",
        Genre: "friendship"
    },
    {
        BookName: "Tales of War",
        AuthorName: "Henry Battle",
        YearOfPublication: 2018,
        Price: 11.50,
        Discount: 0,
        NumberOfPages: 130,
        Condition: "used",
        description: "A soldier recounts tales of battle and sacrifice.",
        Genre: "war"
    },
    {
        BookName: "Intergalactic Hearts",
        AuthorName: "Lily Cosmic",
        YearOfPublication: 2021,
        Price: 14.50,
        Discount: 12,
        NumberOfPages: 100,
        Condition: "new",
        description: "Two lovers torn apart by intergalactic war.",
        Genre: "love"
    },
    {
        BookName: "Soldier's Honor",
        AuthorName: "Jack Brave",
        YearOfPublication: 2016,
        Price: 9.99,
        Discount: 4,
        NumberOfPages: 95,
        Condition: "used",
        description: "A soldier’s battle for honor in a distant world.",
        Genre: "soldier"
    },
    {
        BookName: "Family Beyond Earth",
        AuthorName: "Diana Hearth",
        YearOfPublication: 2020,
        Price: 12.75,
        Discount: 7,
        NumberOfPages: 110,
        Condition: "new",
        description: "A family faces trials while exploring a new planet.",
        Genre: "family"
    },
    {
        BookName: "Starlight Warriors",
        AuthorName: "Max Universe",
        YearOfPublication: 2021,
        Price: 15.99,
        Discount: 10,
        NumberOfPages: 120,
        Condition: "new",
        description: "Soldiers in space fight for the fate of the galaxy.",
        Genre: "sci-fi"
    },
    {
        BookName: "Battle for Freedom",
        AuthorName: "Clara Knight",
        YearOfPublication: 2019,
        Price: 11.25,
        Discount: 5,
        NumberOfPages: 130,
        Condition: "used",
        description: "A war for freedom set on an alien world.",
        Genre: "war"
    },
    {
        BookName: "Cosmic Companions",
        AuthorName: "Chris Nebula",
        YearOfPublication: 2022,
        Price: 13.99,
        Discount: 8,
        NumberOfPages: 115,
        Condition: "new",
        description: "A story of deep friendship across galaxies.",
        Genre: "friendship"
    },
    {
        BookName: "The Space Between Us",
        AuthorName: "Eve Horizon",
        YearOfPublication: 2017,
        Price: 14.50,
        Discount: 5,
        NumberOfPages: 125,
        Condition: "new",
        description: "A love story between two people from rival planets.",
        Genre: "love"
    },
    {
        BookName: "Battle for Eternity",
        AuthorName: "Marcus Steel",
        YearOfPublication: 2018,
        Price: 12.99,
        Discount: 7,
        NumberOfPages: 105,
        Condition: "used",
        description: "Soldiers fight for control of the eternal city in the stars.",
        Genre: "war"
    },
    {
        BookName: "Interstellar Friends",
        AuthorName: "Zoe Starfriend",
        YearOfPublication: 2019,
        Price: 11.50,
        Discount: 0,
        NumberOfPages: 90,
        Condition: "used",
        description: "Two friends explore the universe together.",
        Genre: "friendship"
    },
    {
        BookName: "The Forgotten War",
        AuthorName: "Terry Trench",
        YearOfPublication: 2016,
        Price: 9.99,
        Discount: 2,
        NumberOfPages: 100,
        Condition: "used",
        description: "A soldier’s tale in a war lost to history.",
        Genre: "soldier"
    },
    {
        BookName: "Across the Stars",
        AuthorName: "Amy Sky",
        YearOfPublication: 2020,
        Price: 13.50,
        Discount: 6,
        NumberOfPages: 115,
        Condition: "new",
        description: "A romantic tale that spans galaxies.",
        Genre: "love"
    },
    {
        BookName: "Brotherhood of the Stars",
        AuthorName: "Luke Solis",
        YearOfPublication: 2021,
        Price: 14.99,
        Discount: 8,
        NumberOfPages: 130,
        Condition: "new",
        description: "A group of friends protecting the galaxy from invaders.",
        Genre: "friendship"
    },
    {
        BookName: "The Warrior’s Path",
        AuthorName: "Julius Legion",
        YearOfPublication: 2015,
        Price: 9.50,
        Discount: 4,
        NumberOfPages: 90,
        Condition: "used",
        description: "A soldier’s journey through war-torn planets.",
        Genre: "soldier"
    },
    {
        BookName: "Family Bond",
        AuthorName: "Rose Unity",
        YearOfPublication: 2018,
        Price: 11.99,
        Discount: 3,
        NumberOfPages: 110,
        Condition: "new",
        description: "A family sticks together through a galactic crisis.",
        Genre: "family"
    },
    {
        BookName: "Stellar Combat",
        AuthorName: "David Shields",
        YearOfPublication: 2021,
        Price: 13.99,
        Discount: 10,
        NumberOfPages: 125,
        Condition: "new",
        description: "Epic battles between rival factions in the stars.",
        Genre: "war"
    },
    {
        BookName: "Hearts of the Galaxy",
        AuthorName: "Victoria Love",
        YearOfPublication: 2019,
        Price: 12.50,
        Discount: 5,
        NumberOfPages: 105,
        Condition: "new",
        description: "A love story that defies the laws of space and time.",
        Genre: "love"
    },
    {
        BookName: "Warriors in the Void",
        AuthorName: "Connor Blade",
        YearOfPublication: 2017,
        Price: 10.99,
        Discount: 3,
        NumberOfPages: 100,
        Condition: "used",
        description: "Soldiers fight for survival in the deep void of space.",
        Genre: "soldier"
    },
    {
        BookName: "Friendship Galaxy",
        AuthorName: "Ellie Nebula",
        YearOfPublication: 2020,
        Price: 14.25,
        Discount: 6,
        NumberOfPages: 120,
        Condition: "new",
        description: "A tale of lasting friendship across the galaxy.",
        Genre: "friendship"
    },
    {
        BookName: "The War of Planets",
        AuthorName: "James Mars",
        YearOfPublication: 2022,
        Price: 15.50,
        Discount: 10,
        NumberOfPages: 130,
        Condition: "new",
        description: "A brutal war between two planets on the brink of destruction.",
        Genre: "war"
    },
    {
        BookName: "Cosmic Embrace",
        AuthorName: "Luna Starlight",
        YearOfPublication: 2016,
        Price: 13.00,
        Discount: 0,
        NumberOfPages: 110,
        Condition: "used",
        description: "A love story that spans the entire universe.",
        Genre: "love"
    },
    {
        BookName: "Soldiers of the Starship",
        AuthorName: "Grant Iron",
        YearOfPublication: 2021,
        Price: 12.99,
        Discount: 5,
        NumberOfPages: 115,
        Condition: "new",
        description: "A crew of soldiers defends their starship from invaders.",
        Genre: "soldier"
    },
    {
        BookName: "Galactic Guardians",
        AuthorName: "Brian Cosmos",
        YearOfPublication: 2020,
        Price: 14.99,
        Discount: 8,
        NumberOfPages: 125,
        Condition: "new",
        description: "A group of friends forms an alliance to protect the universe.",
        Genre: "friendship"
    },
    {
        BookName: "Love in the Stars",
        AuthorName: "Selena Galaxy",
        YearOfPublication: 2018,
        Price: 11.50,
        Discount: 2,
        NumberOfPages: 100,
        Condition: "used",
        description: "Two lovers find each other in the vastness of space.",
        Genre: "love"
    },
    {
        BookName: "The Battle for Tomorrow",
        AuthorName: "Jake Trench",
        YearOfPublication: 2019,
        Price: 10.99,
        Discount: 4,
        NumberOfPages: 110,
        Condition: "used",
        description: "Soldiers prepare for the final battle that will decide their fate.",
        Genre: "war"
    },
    {
        BookName: "Friends Across the Universe",
        AuthorName: "Nina Nova",
        YearOfPublication: 2017,
        Price: 12.75,
        Discount: 5,
        NumberOfPages: 95,
        Condition: "used",
        description: "Two friends explore the universe in search of adventure.",
        Genre: "friendship"
    },
    {
        BookName: "Family on the Edge",
        AuthorName: "Evan Stark",
        YearOfPublication: 2021,
        Price: 14.25,
        Discount: 7,
        NumberOfPages: 120,
        Condition: "new",
        description: "A family survives on the edge of a crumbling galaxy.",
        Genre: "family"
    },
        {
        BookName: "Shadow of the Galaxy",
        AuthorName: "Nora Nightshade",
        YearOfPublication: 2021,
        Price: 16.50,
        Discount: 10,
        NumberOfPages: 140,
        Condition: "new",
        description: "A thrilling tale of espionage set in a futuristic galaxy.",
        Genre: "sci-fi"
    },
    {
        BookName: "Heroes of the Void",
        AuthorName: "Cyrus Spacewalker",
        YearOfPublication: 2019,
        Price: 11.00,
        Discount: 5,
        NumberOfPages: 100,
        Condition: "used",
        description: "A group of heroes band together to fight cosmic threats.",
        Genre: "sci-fi"
    },
    {
        BookName: "Tides of War",
        AuthorName: "Bianca Ocean",
        YearOfPublication: 2017,
        Price: 10.75,
        Discount: 4,
        NumberOfPages: 90,
        Condition: "used",
        description: "Battles rage on water worlds, where survival is key.",
        Genre: "war"
    },
    {
        BookName: "Beyond the Stars",
        AuthorName: "Oliver Celestial",
        YearOfPublication: 2020,
        Price: 12.25,
        Discount: 3,
        NumberOfPages: 125,
        Condition: "new",
        description: "A journey of discovery across uncharted territories.",
        Genre: "sci-fi"
    },
    {
        BookName: "Galactic Refugees",
        AuthorName: "Maya Wanderer",
        YearOfPublication: 2022,
        Price: 14.00,
        Discount: 7,
        NumberOfPages: 110,
        Condition: "new",
        description: "The plight of displaced beings seeking a new home.",
        Genre: "sci-fi"
    },
    {
        BookName: "Love on the Edge",
        AuthorName: "Rita Horizon",
        YearOfPublication: 2021,
        Price: 12.50,
        Discount: 5,
        NumberOfPages: 115,
        Condition: "new",
        description: "A romance blossoms in the face of impending doom.",
        Genre: "love"
    },
    {
        BookName: "In the Line of Duty",
        AuthorName: "Sam Duty",
        YearOfPublication: 2018,
        Price: 13.75,
        Discount: 6,
        NumberOfPages: 130,
        Condition: "used",
        description: "A soldier's mission leads to unexpected consequences.",
        Genre: "war"
    },
    {
        BookName: "Alliance of Stars",
        AuthorName: "Penny Unity",
        YearOfPublication: 2020,
        Price: 15.00,
        Discount: 8,
        NumberOfPages: 140,
        Condition: "new",
        description: "Factions unite to combat a common enemy.",
        Genre: "sci-fi"
    },
    {
        BookName: "Love Across Dimensions",
        AuthorName: "Felix Quantum",
        YearOfPublication: 2022,
        Price: 13.50,
        Discount: 5,
        NumberOfPages: 120,
        Condition: "new",
        description: "Two lovers from different dimensions seek to reunite.",
        Genre: "love"
    },
    {
        BookName: "Echoes of the Past",
        AuthorName: "Tim Historian",
        YearOfPublication: 2019,
        Price: 10.50,
        Discount: 0,
        NumberOfPages: 95,
        Condition: "used",
        description: "A soldier reflects on the battles that shaped his life.",
        Genre: "war"
    },
    {
        BookName: "The Last Guardian",
        AuthorName: "Leo Protector",
        YearOfPublication: 2021,
        Price: 14.99,
        Discount: 10,
        NumberOfPages: 135,
        Condition: "new",
        description: "One guardian's fight to save a dying galaxy.",
        Genre: "sci-fi"
    },
    {
        BookName: "Interstellar Expeditions",
        AuthorName: "Zara Explorer",
        YearOfPublication: 2020,
        Price: 12.99,
        Discount: 5,
        NumberOfPages: 115,
        Condition: "new",
        description: "Explorers venture into the unknown reaches of space.",
        Genre: "sci-fi"
    },
    {
        BookName: "Bravery and Sacrifice",
        AuthorName: "Paul Courage",
        YearOfPublication: 2018,
        Price: 11.50,
        Discount: 3,
        NumberOfPages: 100,
        Condition: "used",
        description: "A soldier's heart-wrenching choices during wartime.",
        Genre: "war"
    },
    {
        BookName: "Bonds of Friendship",
        AuthorName: "Ella Ally",
        YearOfPublication: 2021,
        Price: 13.25,
        Discount: 6,
        NumberOfPages: 120,
        Condition: "new",
        description: "Friends navigate challenges and strengthen their bonds.",
        Genre: "friendship"
    },
    {
        BookName: "Futures Untold",
        AuthorName: "Graham Vision",
        YearOfPublication: 2022,
        Price: 14.75,
        Discount: 5,
        NumberOfPages: 130,
        Condition: "new",
        description: "A tale of hope in a dystopian future.",
        Genre: "sci-fi"
    },
    {
        BookName: "Twilight Romance",
        AuthorName: "Nina Dusk",
        YearOfPublication: 2019,
        Price: 10.99,
        Discount: 2,
        NumberOfPages: 90,
        Condition: "used",
        description: "A romance blossoms as twilight descends on their worlds.",
        Genre: "love"
    },
    {
        BookName: "Warriors of Light",
        AuthorName: "Liam Bright",
        YearOfPublication: 2020,
        Price: 15.25,
        Discount: 8,
        NumberOfPages: 140,
        Condition: "new",
        description: "A group of warriors battles darkness to save the light.",
        Genre: "war"
    },
    {
        BookName: "Chronicles of War",
        AuthorName: "Zane Battle",
        YearOfPublication: 2021,
        Price: 11.99,
        Discount: 3,
        NumberOfPages: 110,
        Condition: "new",
        description: "A soldier's chronicles through the trials of war.",
        Genre: "war"
    },
    {
        BookName: "Paths of Friendship",
        AuthorName: "Sophia Trust",
        YearOfPublication: 2022,
        Price: 12.99,
        Discount: 5,
        NumberOfPages: 115,
        Condition: "new",
        description: "Two friends embark on a journey that tests their bond.",
        Genre: "friendship"
    }
];


module.exports = { data: sampleComic };